feat: added download entire db as csv/excel
yashshah1/mongo-utils pull request #2
Opened 2020-10-04 18:30 UTC by vasusharma7

For now :
It downloads entire database as CSV or EXCEL.
Things lacking:
- checking corner cases;
- code cleaning;
- making code more modular;
etc...

2020-10-05 15:44 UTC, yashshah1 commented on package.json
> +    "json2xls": "^0.1.2",
Do we need all these?

2020-10-05 16:03 UTC, vasusharma7 commented on package.json
> +    "json2xls": "^0.1.2",
No, I have deleted the unused ones and committed the changes !

2020-10-12 06:47 UTC, yashshah1 requested changes

2020-10-12 06:47 UTC, yashshah1 commented on package.json
>      "@types/mongodb": "^3.5.27",
Add these to dev dependencies

2020-10-12 06:55 UTC, yashshah1 requested changes

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +  type: string;
```suggestion
  type: "json" | "csv" | "excel";
```

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +  const type: string = params.type.toLowerCase();
```suggestion
  const {mongoURI, database, type} params;
```

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +    const db: any = await client.db(database);
Avoid any types, `client.db` will assign a type to `db`

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +      if (database == dbObject.name) {
```suggestion
      if (database === dbObject.name) {
```

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +    for (const dbObject of fetchDbs.databases) {
Is there no other way, other than iterating through all of the databases?

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +    const dbDir: string = process.cwd() + "/" + database + "_" + params.type;
```suggestion
    const dbDir: string = `${database}_${params.type}`;
```

2020-10-12 06:55 UTC, yashshah1 commented on src/download/download.ts
> +      async (obj: any): Promise<void> => {
Avoid any.

2020-10-12 06:55 UTC, yashshah1 commented on src/download/utils.ts
> +export default { preprocessRecords };
Don't combine named and unnamed exports.
Either `export preprocessRecords` or `export const preprocessRecords = () => {...}`

And import them as `import * as utils from "./utils"`

2020-10-12 07:02 UTC, vasusharma7 commented on src/download/download.ts
> +    const db: any = await client.db(database);
No, actually it doesn't return any error or indication on connecting to a non-existing databases.

2020-10-12 07:02 UTC, vasusharma7 commented on src/download/download.ts
> +    for (const dbObject of fetchDbs.databases) {
No, actually it doesn't return any error or indication on connecting to a non-existing databases.

2020-11-02 12:13 UTC, merged