feat: create function to upload json data to database
yashshah1/mongo-utils pull request #4
Opened 2020-10-09 14:55 UTC by Pranav2612000

Fixes #3

2020-10-10 10:28 UTC, yashshah1 commented on .eslintrc.js
> +    "@typescript-eslint/no-empty-interface": "off",
Let's not. Empty interfaces are as good as `any`

2020-10-10 10:29 UTC, yashshah1 commented on package.json
> +    "start": "nodemon index.js",
Why do we need nodemon, given that we don't use a port listener?
Also, we haven't set up anything for a live compile of changed ts files, maybe we should do that. I think tsc has a `--watch` flag

2020-10-10 10:45 UTC, yashshah1 requested changes

2020-10-10 10:45 UTC, yashshah1 commented on src/upload/upload.ts
> +type documents = Array<document>;
Suggestion 1: 
```diff
- interface document {}
- type documents = Array<document>;
+ type documents = Array<any>
```
Alternatievly declare a type for a JSON object in another file. Look at https://github.com/yashshah1/sql-query-json/blob/master/src/adapters/adapterInterfaces.ts#L1L9

2020-10-10 10:45 UTC, yashshah1 commented on src/upload/upload.ts
> +  }
```suggestion
	await client.connect();
    const db = client.db(dbName);	
    Object.keys(data).forEach((collectionName: string & keyof uploadData) => {
      if (data[collectionName] === null || data[collectionName].length === 0) {
        console.log(
          collectionName + " has no data to be uploaded. Skipping...",
        );
        return;
      }

      const collection: Collection = db.collection(collectionName);
      collection.insertMany(data[collectionName]);
      console.log(collectionName + " uploaded successfully");
    });
  } catch (err) {
    console.log(err);
  }
```

With await we don't need to provide a callback

2020-10-10 10:45 UTC, yashshah1 commented on package.json
> +    "@types/node": "^14.11.8",
Can we shift these to devDependencies?

2020-10-10 14:04 UTC, Pranav2612000 commented on .eslintrc.js
> +    "@typescript-eslint/no-empty-interface": "off",
Ok.

2020-10-10 14:05 UTC, Pranav2612000 commented on package.json
> +    "start": "nodemon index.js",
Haven't changed in this file. Will do that. What do you suggest for "start" ?

2020-10-10 14:06 UTC, Pranav2612000 commented on src/upload/upload.ts
> +  }
Somehow this didn't work for me. Will try again.

2020-10-10 14:06 UTC, Pranav2612000 commented on package.json
> +    "@types/node": "^14.11.8",
On it.

2020-10-10 19:36 UTC, Pranav2612000 commented
Updated. @yashshah1 Please take a look.

2020-10-11 05:53 UTC, yashshah1 commented on package.json
> +    "start": "nodemon index.js",
I would argue that we don't need a start, since it is a CLI, we'd have to run it with the feature we're testing. Either upload/download?

2020-10-11 05:54 UTC, yashshah1 commented on src/upload/upload.ts
> +  }
The code I've suggested probably isn't accurate. I just saw the doc which said, `await client.connect()` is enough to make a connection, which throws an exception if it fails

2020-10-11 06:11 UTC, yashshah1 requested changes

2020-10-11 06:11 UTC, yashshah1 commented on src/upload/upload.ts
> +type documents = Array<any>;
Can we shift to using a JSON Interface?
```suggestion
interface MakeshiftJSONInterface {
  [key: string]:
    | string
    | number
    | boolean
    | null
    | MakeshiftJSONInterface
    | Array<MakeshiftJSONInterface>;
}
type documents = Array<MakeshiftJSONInterface>;
```

2020-10-11 09:35 UTC, Pranav2612000 commented on .eslintrc.js
> +  ignorePatterns: ["**/lib/*"],
We don't want eslint to check the compiled files in /lib/ . Many of them are compiled in a non prettier compatible format, and prettier gives errors and warnings. What do you think?

2020-10-11 09:41 UTC, Pranav2612000 commented on src/upload/upload.ts
> +type documents = Array<any>;
Done. Please take a look.

2020-10-12 06:35 UTC, yashshah1 commented on .eslintrc.js
> +  ignorePatterns: ["**/lib/*"],
I think instead of blacklisting a folder, we could only white list the src folder. Which could mean changing the lint script to something like `eslint 'src/**/*.ts' --quiet --fix`. I think I forgot to change the lint script when I copied the config from another project

2020-10-12 06:45 UTC, yashshah1 requested changes

2020-10-12 06:45 UTC, yashshah1 commented on src/upload/upload.ts
> +  const data: uploadData = params.data;
```suggestion
  const {dbName, mongoURI, data} = params;
```

2020-10-12 06:45 UTC, yashshah1 commented on src/upload/upload.ts
> +      }
Empty collections could be intentional, can we add this as a flag instead, where the default behaviour is to upload?

2020-10-12 06:45 UTC, yashshah1 commented on src/upload/upload.ts
> +      collection.insertMany(data[collectionName]);
```suggestion
      await collection.insertMany(data[collectionName]);
```

Or better still, add this to an array of `promises` and before the `return` add:
```typescript
await Promise.all(promises);
return;
```

2020-10-12 06:45 UTC, yashshah1 commented on src/upload/upload.ts
> +    console.log(err);
Assuming people will use this as a CLI, a failed run of the code should return a non-zero status code. The only way I can think of doing that right now is adding `process.exit(1)` below `console.log`. Any suggestions?

2020-10-12 06:48 UTC, Pranav2612000 commented on src/upload/upload.ts
> +  }
Changed. Take a look.

2020-10-12 08:43 UTC, Pranav2612000 commented on src/upload/upload.ts
> +    console.log(err);
Let's do that.

2020-10-12 08:50 UTC, Pranav2612000 commented on src/upload/upload.ts
> +  const data: uploadData = params.data;
Done.

2020-10-12 08:54 UTC, Pranav2612000 commented on src/upload/upload.ts
> +      }
Yes. A flag would be more appropriate, but I feel lets work on it later. Lets have the basic function merged first. What do you think?

2020-10-12 09:15 UTC, yashshah1 commented on src/upload/upload.ts
> +      }
Works (Y)

2020-10-12 09:36 UTC, Pranav2612000 commented on src/upload/upload.ts
> +      collection.insertMany(data[collectionName]);
Done.

2020-10-12 09:43 UTC, Pranav2612000 commented
Pushed. Major Changes - 1. Use Promises.all() 2. create a new test.js file for tests(will work for now, will need to organize test properly later as modules increase)

2020-11-02 12:14 UTC, merged